## Regularni izrazi - Uparivanje šablona sa regularnim izrazima

Možda ste upoznati sa pretraživanjem teksta pritiskom na CTRL-F i unošenjem reči koje tražite. *Regularni izrazi* idu jedan korak dalje: omogućavaju vam da odredite *obrazac* teksta za pretragu. Možda ne znate tačan telefonski broj preduzeća, ali ako živite u Srbiji, znate da će to biti tri cifre, zatim crtica, a zatim još sedam cifara (eventualno razdvojenih crticama). Ovako, kao čovek, znate telefonski broj kad ga vidite: 064-555-1234 je telefonski broj, ali 4.155.551.234 nije.

Takođe prepoznajemo i razne druge tekstualne obrasce svakog dana: adrese e-pošte imaju @ simbole u sredini, srpski brojevi socijalnog osiguranja imaju devet cifara i dve crtice, URL adrese veb lokacija često imaju tačke i kose crte, naslovi vesti koriste velika slova, hashtagovi na društvenim mrežama počinju sa # i ne sadrže razmake, i još mnogo toga.

Regularni izrazi su korisni, ali malo onih koji nisu programeri znaju za njih iako većina modernih uređivača teksta i procesora za obradu teksta, kao što su Microsoft Word ili OpenOffice, imaju funkcije i pronalaženja i zamene koje mogu pretraživati na osnovu regularnih izraza. Regularni izrazi uštede vreme, ne samo za korisnike softvera, već i za programere. U stvari, pisac ove tehnike Cory Doctorow tvrdi da bismo trebali učiti regularne izraze čak i pre programiranja:

Poznavanje regularnih izraza može značiti razliku između rešavanja problema u 3 koraka i rešavanja u 3.000 koraka. Neki problemi koji se mogu rešiti sa nekoliko pritiskanja tastera mogu drugim ljudima trajati dane zamornog rada sklonog greškama.

U ovom poglavlju naučićemo da pišemo programe za pronalaženje tekstualnih obrazaca bez upotrebe regularnih izraza, a zatim ćemo videti kako koristiti regularne izraze kako bi kod bio znatno manje obiman. Pokazaću vam osnove podudaranja sa regularnim izrazima, a zatim ću preći na neke moćnije funkcije, kao što su zamena stringa i stvaranje sopstvenih klasa znakova. Konačno, na kraju poglavlja napisaćete program koji može automatski da izdvoji brojeve telefona i adrese e-pošte iz bloka teksta.

### Pronalaženje obrazaca teksta bez regularnih izraza

Recimo da želite da pronađete američki telefonski broj u stringu. Znate obrazac ako ste iz Srbije: tri broja, crtica, tri broja, crtica i četiri broja. 
Evo primera: 415-555-4242. Koristimo funkciju nazvanu `is_phone_number()` da proverimo da li se string podudara sa ovim šablonom, vraćajući True ili False.

In [1]:
def is_phone_number(text):
    if len(text) != 12:
        return False
    for i in range(0, 3):
        if not text[i].isdecimal():
            return False
    if text[3] != '-':
        return False
    for i in range(4, 7):
        if not text[i].isdecimal():
            return False
    if text[7] != '-':
        return False
    for i in range(8, 12):
         if not text[i].isdecimal():
            return False
    return True

In [2]:
print('Da li je 415-555-4242 telefonski broj?')
print(is_phone_number('415-555-4242'))

Da li je 415-555-4242 telefonski broj?
True


In [3]:
print('Da li je Petar Petrović telefonski broj?')
print(is_phone_number('Moshi moshi'))

Da li je Petar Petrović telefonski broj?
False


Ako želite da pronađete telefonski broj u većem stringu, moraćete da dodate još više koda da biste pronašli obrazac telefonskog broja:

In [4]:
message = 'Pozovi me sutra na broj telefona 415-555-1011. Moj broj telefona u kancelariji je 415-555-9999.'
for i in range(len(message)):
    chunk = message[i:i+12]
    if is_phone_number(chunk):
        print('Pronađen broj telefona: ' + chunk)
print('Gotovo')

Pronađen broj telefona: 415-555-1011
Pronađen broj telefona: 415-555-9999
Gotovo


Iako je string u poruci u ovom primeru kratak, on bi mogao biti dugačak milion znakova, a program bi i dalje radio za manje od sekunde. Sličan program koji 
pronalazi brojeve telefona pomoću regularnih izraza takođe bi se pokrenuo za manje od sekunde, ali regularni izrazi ubrzavaju pisanje ovih programa.

#### Pronalaženje obrazaca teksta sa regularnim izrazima

Prethodni program za pronalaženje telefonskog broja funkcioniše, ali koristi mnogo koda da bi uradio nešto ograničeno: funkcija `is_phone_number()` ima 17 redova, 
ali može pronaći samo jedan obrazac brojeva telefona. Šta je sa brojem telefona formatiranim poput 415.555.4242 ili (415) 555-4242? Šta ako telefonski broj ima 
dodatak, na primer 415-555-4242 x99? Funkcija `is_phone_number()` neće uspeti da ih potvrdi. Možete dodati još koda za ove dodatne obrasce, ali postoji lakši način.

Regularni izrazi, skraćeno nazvani *regexes*, opisi su obrasca teksta. Na primer, a `\d` u regularnom izrazu označava cifreni znak - to jest bilo koji pojedinačni broj od 0 do 9. Redovni izraz `\d\d\d-\d\d\d-\d\d\d\d` koristi Pithon za podudaranje sa istim tekstualnim obrascem kao i prethodna funkcija `is_phone_number()`: string od tri broja, crtica, još tri broja, još jedna crtica i četiri broja. Bilo koji drugi string ne bi se podudarao sa `\d\d\d-\d\d\d-\d\d\d\d` regularnim izrazom.

Ali regularni izrazi mogu biti mnogo sofisticiraniji. Na primer, dodavanje mesta 3 u zagradama ({3}) nakon uzorka je kao da kažete: „Poravnajte ovaj obrazac tri puta. Dakle, nešto kraći regularni izraz `\d{3}-\d{3}-\d{4}` takođe se podudara sa ispravnim formatom telefonskog broja.

### Kreiranje Regex objekata

Sve regex funkcije u Pythonu se nalaze u modulu `re`.

In [7]:
import re

Ako se prosledi vrednost stringa koji predstavlja vaš regularni izraz funkciji `re.compile()` ona vraća objekat `Regex` šablona (ili jednostavno `Regex` objekat).


Da biste kreirali `Regex` objekat koji se podudara sa uzorkom (šablonom) telefonskog broja, unesite sledeće: 
(Zapamtite da `\d` znači „cifreni znak“, a `\d\d\d-\d\d\d-\d\d\d\d` je regularni izraz za obrazac telefonskog broja.)

In [8]:
phone_num_regex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')

Sada `phone_number_regex` promenljiva sadrži `Regex` objekat.

#### Uparivanje Regex objekata

Metoda `search()` `Regex` objekta pretražuje string koji mu je prosleđen za bilo koje podudaranje sa regularnim izrazom. Metoda `search()` će vratiti None ako 
obrazac regularnog izraza nije pronađen u stringu. Ako je obrazac pronađen, metoda `search()` vraća objekt `Match`, koji ima metodu `group()` koja će vratiti 
stvarni podudarni tekst iz pretraživanog stringa. (Ubrzo ću objasniti grupe.) Na primer, unesite sledeće:

In [9]:
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
mo = phoneNumRegex.search('Moj broj telefona je 062-555-4242.')
print('Pronađen broj telefona: ' + mo.group())

Pronađen broj telefona: 062-555-4242


Promenljiva `mo` je ime za `Match` objekte. Ovaj primer možda izgleda komplikovano na početku, ali je mnogo kraći od prethodno napisanih programa.

Ovde prosleđujemo željeni obrazac `re.compile()` i rezultirajući `Regex` objekat čuvamo u `phoneNumRegex`. Zatim pozivamo `search()` na `phoneNumRegex` i prenosimo 
`search()` string za koji želimo da ispitamo podudaranje tokom pretraživanja. Rezultat pretrage čuva se u promenljivoj `mo`. U ovom primeru znamo da će se naš 
obrazac naći u stringu, pa znamo da će se vratiti objekt `Match`. Znajući da `mo` sadrži objekt podudaranja, a ne null vrednost None, možemo pozvati `group()` na 
`mo` da vratimo podudaranje. Pisanje `mo.group()` unutar našeg poziva funkcije `print()` prikazuje celo podudaranje, 415-555-4242.

#### Pregled podudaranja regularnih izraza

Iako postoji nekoliko koraka za upotrebu regularnih izraza u Pithonu, svaki korak je prilično jednostavan

1. Uvezite regex modul sa `import re`.
2. Stvorite `Regex` objekat pomoću funkcije `re.compile()`. (Ne zaboravite da koristite sirovi string.) 
3. Prenesite string koji želite da pretražite metodi `search()` `Regex` objekta. Ona vraća objekt podudaranje `Match`. 
4. Pozovite metod `group()` objekta `Match` da biste vratili string stvarnog podudarnog teksta.

### Još o uparivanju šablona sa regularnim izrazima

Sada kada znate osnovne korake za kreiranje i pronalaženje objekata regularnih izraza pomoću Pithona, spremni ste da isprobate neke od njihovih moćnijih mogućnosti 
usklađivanja uzoraka/šablona.

#### Grupisanje sa zagradama

Recimo da želite da odvojite pozivni broj od ostatka telefonskog broja. Dodavanjem zagrada stvoriće se grupe u regularnom izrazu: `(\d\d\d)-(\d\d\d-\d\d\d\d)`. 
Tada možete koristiti metodu objekta podudaranja `group()` da biste uzeli odgovarajući tekst iz samo jedne grupe.

Prvi skup zagrada u nizu regularnog izraza biće grupa 1. Drugi skup biće grupa 2. Prenošenjem celog broja 1 ili 2 na metodu objekta podudaranja `group()` možete da 
preuzmete različite delove podudarnog teksta. Prosleđivanje 0 ili ništa metodi `group()` vratiće ceo podudarni tekst. Unesimo sledeće:

In [10]:
phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('Moj broj telefona je 065-555-4242.')

In [11]:
mo.group(1) 

'065'

In [12]:
mo.group(2)

'555-4242'

In [13]:
mo.group(0) 

'065-555-4242'

In [14]:
mo.group() 

'065-555-4242'

Ako želite da preuzmete sve grupe odjednom, koristite metodu `groups()` - obratite pažnju na oblik množine za ime.

In [15]:
mo.groups()

('065', '555-4242')

In [23]:
provajder, glavniBroj = mo.groups()

In [24]:
print(provider)

065


In [25]:
print(glavniBroj)

555-4242


Budući da `mo.groups()` vraća više vrednosti, trikom višestrukog dodeljivanja možete da dodelite svaku vrednost zasebnoj promenljivoj, kao u prethodnom redu.

Zagrade imaju posebno značenje u regularnim izrazima, ali šta radite ako treba da podudarite zagradu u svom tekstu? Na primer, možda telefonski brojevi kojima 
pokušavate da se podudaraju imaju pozivni broj u zagradama. U ovom slučaju morate da izbegnete znakove ( i ) pomoću kose crte. Unesite sledeće

In [26]:
phoneNumRegex = re.compile(r'(\(\d\d\d\)) (\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search('Moj broj telefona je (060) 555-4242.')

In [27]:
mo.group(1)

'(060)'

In [28]:
mo.group(2)

'555-4242'

Znakovi za izlazak `(` i `)` u sirovom stringu prosleđenom u `re.compile()` podudaraće se sa stvarnim znakovima u zagradama. U regularnim izrazima, sledeći znakovi 
imaju posebna značenja: ` .  ^  $  *  +  ?  {  }  [  ]  \  |  (  )`

Ako želite da otkrijete ove znakove kao deo svog tekstualnog obrasca, morate da ih ispisujete kosom crtom: </br> \\.  \\^  \\$  \\*  \\+  \\?  \\{  \\}  \\[  ... 

Obavezno dvaput proverite da li ste u regularnom izrazu pogrešno napisali zagrade `\(` i `\)` i zagrade `(` i `)`. Ako dobijete poruku o grešci o „nedostajućim“ ili „neuravnoteženim zagradama“, možda ste zaboravili da uključite zatvarajući nepregrađene zagrade za grupu, kao u ovom primeru:

In [20]:
re.compile(r'(\(Zagrade\)')

error: missing ), unterminated subpattern at position 0

Poruka o grešci govori vam da postoji početna zagrada u indeksu 0 stringa `'r(\ (zagrade \)'` kojem nedostaju odgovarajuće zagrade u zatvaranju.

#### Povezivanje više grupa sa cevovodom (pipe)

Karakter `|` naziva se cev/lula. Možete ga koristiti bilo gde gde želite da se podudara sa jednim od mnogih izraza. Na primer, regularni izraz `r'Batman|Tina Fei'` podudaraće se sa `'Batman'` ili `'Tina Fei'`.

Kada se i `Batman` i `Tina Fei` pojave u pretraživanom stringu, prva pojava odgovarajućeg teksta vratiće se kao objekt Match. Unesimo sledeće:

In [29]:
heroRegex = re.compile(r'Batman|Tina Fey')

In [30]:
mo1 = heroRegex.search('Batman and Tina Fey')

In [31]:
mo1.group()

'Batman'

In [32]:
mo2 = heroRegex.search('Tina Fey and Batman')

In [33]:
mo2.group()

'Tina Fey'

*Primedba:* Možemo pronaći sva podudaranja metodom `findall()`, ali o tome kasnije.

Takođe možete koristiti cev da utvrdite podudaranje sa jednim od nekoliko obrazaca kao deo vašeg regularnog izraza. Na primer, recimo da želite da pronađete podudaranje sa bilo  kojim stringom „Batman“, „Batmobile“, „Batcopter“ i „Batbat“. Budući da svi ovi nizovi počinju sa Bat, bilo bi lepo kada biste taj prefiks mogli odrediti samo jednom. To se može uraditi pomoću zagrada. Unesite sledeće:

In [34]:
batRegex = re.compile(r'Bat(man|mobile|copter|bat)')

In [35]:
mo = batRegex.search('Batmobile lost a wheel')

In [36]:
mo.group()

'Batmobile'

In [37]:
mo.group(1)

'mobile'

Poziv metode `mo.group()` vraća puni podudarni tekst `'Batmobile'`, dok `mo.group(1)` vraća samo deo podudarnog teksta unutar prve grupe zagrada, `'mobile'`. 
Upotrebom znaka lule i grupisanjem zagrada možete odrediti nekoliko alternativnih obrazaca za koje želite da se vaš regularni izraz podudara.

Ako tražite podudaranje sa stvarnim znakom cevi, izbegnite ga kosom crtom, poput `\|`.

#### Opciono uparivanje sa znakom pitanja

Ponekad postoji obrazac za koji želite da se podudara samo opciono. Odnosno, regularni izraz treba da pronađe podudaranje bez obzira na to da li je taj deo teksta 
tamo. Znak ? označava grupu koja mu prethodi kao opcioni deo šablona. Na primer, ako unesemo sledeće:

In [38]:
batRegex = re.compile(r'Bat(wo)?man')

In [39]:
mo1 = batRegex.search('The Adventures of Batman')

In [40]:
mo1.group()

'Batman'

In [41]:
mo2 = batRegex.search('The Adventures of Batwoman')

In [42]:
mo2.group()

'Batwoman'

Deo `(wo)?` deo regularnog izraza znači da je obrazac `wo` neobavezna grupa. Redovni izraz će odgovarati tekstu koji sadrži nula instanci ili jednu instancu `wo`. 
Zbog toga se regularni izraz podudara i sa „Batwoman“ i „Batman“.

Koristeći raniji primer broja telefona, možete da naterate regularni izraz da traži brojeve telefona koji imaju ili nemaju pozivni broj. Unesimo sledeće:

In [43]:
phoneRegex = re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')

In [44]:
mo1 = phoneRegex.search('My number is 415-555-4242')

In [45]:
mo1.group()

'415-555-4242'

In [46]:
mo2 = phoneRegex.search('My number is 555-4242')

In [47]:
mo2.group()

'555-4242'

Znak `?` možete zamisliti kao što je rečeno: „Uparite nijednu ili jednu grupu koja prethodi ovom znaku pitanja.“

Ako vam treba podudaranje stvarnog znaka pitanja, to činite se sa `\?`.

#### Nula ili više uparivanja sa zvezdicom

Znak `*` (zvezdica) znači „podudaranje nula ili više puta“ - grupa koja prethodi zvezdici može se pojaviti bilo koji broj puta u tekstu. Može biti potpuno odsutan ili ponavljati iznova i iznova. Pogledajmo ponovo primer Betmena.

In [48]:
batRegex = re.compile(r'Bat(wo)*man')

In [49]:
mo1 = batRegex.search('The Adventures of Batman')

In [50]:
mo1.group()

'Batman'

In [51]:
mo2 = batRegex.search('The Adventures of Batwoman')

In [52]:
mo2.group()

'Batwoman'

In [53]:
mo3 = batRegex.search('The Adventures of Batwowowowoman')

In [54]:
mo3.group()

'Batwowowowoman'

Za „Batman“, `(wo)*` deo regularnog izraza podudara se sa nula instanci `wo` u stringu; za „Batwoman“, `(wo)*` se podudara sa jednom instancom `wo`; a za „Batwowowowoman“, `(wo)*` odgovara četiri slučaja `wo`.

Ako trebate podudarati stvarni znak zvezde, prefiksu zvezde u regularnom izrazu dodajte kosu kosu crtu, `\*`.

#### Jedno ili više uparivanja sa plusom

Dok `*` znači „podudaranje nula ili više puta“, `+` (ili plus) znači „podudaranje jednom ili više puta“. Za razliku od zvezde, koja ne zahteva da se njena grupa pojavljuje u podudarnom stringu, grupa koja prethodi plusu mora se pojaviti najmanje jednom. Nije neobavezna. Unesite sledeće i uporedite regeksima sa zvezdom u prethodnom odeljku:

In [55]:
batRegex = re.compile(r'Bat(wo)+man')

In [56]:
mo1 = batRegex.search('The Adventures of Batwoman')

In [57]:
mo1.group()

'Batwoman'

In [58]:
mo2 = batRegex.search('The Adventures of Batwowowowoman')

In [59]:
mo2.group()

'Batwowowowoman'

In [60]:
mo1 = batRegex.search('The Adventures of Batman')

In [61]:
mo1 == None

True

Regex `Bat(wo)+` se neće podudarati sa stringom „The Adventures of Batman“, jer je za znak plus potreban bar jedno pojavljivanje `wo`.

Ako trebate podudarati sa stvarnim znakom plusa, prefiksujte znak plus sa kosom crtom: `\+`.

#### Uparivanje specifičan broj puta sa zagradama

Ako imate grupu koju želite da ponovite određeni broj puta, sledite grupu u svom regularnom izrazu sa brojem u zagradama. Na primer, regularni izraz `(Ha){3}` će se 
podudarati sa stringom „HaHaHa“, ali se neće podudarati sa „HaHa“, jer poslednji ima samo dva ponavljanja iz grupe (Ha).

Umesto jednog broja, možete odrediti opseg tako što ćete između zagrada napisati minimum, zarez i maksimum. Na primer, regularni izraz `(Ha){3,5}` će se podudarati 
sa „HaHaHa“, „HaHaHaHa“ i „HaHaHaHaHa“. 

Takođe možete izostaviti prvi ili drugi broj u zagradama da biste ostavili minimum ili maksimum bez ograničenja. Na primer, `(Ha){3,}` će se podudarati sa tri ili 
više primeraka grupe (Ha), dok će se `(Ha){,5}` podudarati sa nula do pet primeraka. Zagrade mogu pomoći da vaši regularni izrazi budu kraći. Ova dva regularna 
izraza se podudaraju sa identičnim obrascima:

`(Ha){3}`  

`(Ha)(Ha)(Ha)`

I ova dva regularna izraza se takođe podudaraju sa identičnim obrascima:

`(Ha){3,5}`

`((Ha)(Ha)(Ha))|((Ha)(Ha)(Ha)(Ha))|((Ha)(Ha)(Ha)(Ha)(Ha))`

Unesimo sledeće:

In [67]:
 haRegex = re.compile(r'(Ha){3}')

In [68]:
mo1 = haRegex.search('HaHaHa')

In [69]:
mo1.group()

'HaHaHa'

In [70]:
mo2 = haRegex.search('Ha')

In [71]:
mo2 == None

True

Ovde se `(Ha){3}` podudara sa „HaHaHa“, ali ne i sa „Ha“. Pošto se ne podudara sa „Ha“, `search()` vraća `None`.

#### Pohlepno i nepohlepno podudaranje

Budući da se `(Ha){3,5}` može podudarati sa tri, četiri ili pet primeraka `Ha` u nizu 'HaHaHaHaHa', možda se pitate zašto poziv objekta `Match` u `group()` 
u prethodnom primeru zagrade vraća 'HaHaHaHaHa' umesto kraće mogućnosti. Na kraju, „HaHaHa“ i „HaHaHaHa“ su takođe važeća podudaranja regularnog izraza `(Ha){3,5}`.

Pithonovi regularni izrazi su podrazumevano pohlepni, što znači da će se u dvosmislenim situacijama podudarati sa najdužim mogućim stringom. Nepohlepna 
(takođe nazvana lenja) zagrada, koja se podudara sa najkraćim mogućim stringom, ima završnu zagradu praćenu znakom pitanja.

Unesite sledeće i uočite razliku između pohlepnih i ne pohlepnih oblika zagrada koje pretražuju isti string:

In [72]:
greedyHaRegex = re.compile(r'(Ha){3,5}')

In [73]:
mo1 = greedyHaRegex.search('HaHaHaHaHa')

In [74]:
mo1.group()

'HaHaHaHaHa'

In [75]:
nongreedyHaRegex = re.compile(r'(Ha){3,5}?')

In [76]:
mo2 = nongreedyHaRegex.search('HaHaHaHaHa')

In [77]:
mo2.group()

'HaHaHa'

Imajte na umu da upitnik može imati dva značenja u regularnim izrazima: proglašavanje ne pohlepnog podudaranja ili označavanje opcionalne grupe. Ova značenja su 
potpuno nepovezana.

#### Metod `findall()`

Pored metode `search()`, Regex objekti imaju i metod `findall()`. Dok će `search()` vratiti objekt podudaranja prvog podudarnog teksta u pretraživanom string, 
metod `findall()` vratit će stringove svakog podudaranja u pretraživanom stringu. Da biste videli kako `search()` vraća objekt podudaranja samo na prvoj instanci 
podudarnog teksta, unesite sledeće u radnu ćeliju:

In [78]:
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')

In [79]:
mo = phoneNumRegex.search('Cell: 415-555-9999 Work: 212-555-0000')

In [80]:
mo.group()

'415-555-9999'

S druge strane, `findall()` neće vratiti objekt `Match` već listu stringova - *sve dok u regularnom izrazu nema grupa*. Svaki string na listi je deo pretraživanog 
teksta koji se podudara sa regularnim izrazom. U interaktivn ćeliju unesite sledeće:

In [81]:
phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d') # nema grupa

In [82]:
phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')

['415-555-9999', '212-555-0000']

Ako u regularnom izrazu postoje grupe, tada će `findall()` vratiti listu n-torki. Svaka n-torka predstavlja pronađeno podudaranje, a njene stavke su usklađeni 
stringovi za svaku grupu u regularnom izrazu. Da biste videli funkciju `findall()`, u interaktivnu ćeliju unesite sledeće (imajte na umu da regularni izraz 
koji se kompajlira sada ima grupe u zagradama):

In [83]:
phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d)-(\d\d\d\d)') # ima grupa

In [84]:
phoneNumRegex.findall('Cell: 415-555-9999 Work: 212-555-0000')

[('415', '555', '9999'), ('212', '555', '0000')]

Da rezimiramo šta metoda `findall()` vraća, upamtite sledeće:

- Kada se pozove regularni izraz bez grupa, kao što je `\d\d\d-\d\d\d-\d\d\d\d`, metoda `findall()` vraća listu uparenih stringova, kao što je `['415-555-9999', '212-555-0000']`. 
- Kada se pozove na regularni izraz koji ima grupe, kao što je `(\d\d\d)-(\d\d\d)-(\d\d\d\d)`, metoda `findall()` vraća listu nizova (po jedan niz za svaku grupu), kao što je `[('415', '555', '9999'), ('212', '555', '0000')]`.
    

#### Klase karaktera

U ranijem primeru regularnog izraza telefonskog broja saznali ste da `\d` može predstavljati bilo koju numeričku cifru. Odnosno, `\d` je skraćenica za regularni 
izraz `(0|1|2|3|4|5|6|7|8|9)`. Postoji mnogo takvih stenografskih klasa znakova, kako je prikazano u tabeli 7-1.

Skraćeni kodovi za uobičajene klase karaktera

Skraćenica za klasu karaktera |  Reprezentuje
:---------------------------:| :-----------------
**\d**                        | Bilo koja numerička cifra od 0 do 9
**\D**                        | Bilo koji karakter koji *nije* numerička cifra od 0 do 9
**\w**                        | Bilo koje slovo, numerička cifra ili karakter za indeks _  (Shvatite kao karaktere kojim formiramo reči)
**\W**                        | Bilo koji karakter koji *nije* slovo, numerička cifra ili karakter za indeks _
**\s**                        | Bilo koji razmak (belina), tabulator ili karakter za kraj reda (Shvatite kao znakovi za razmak)
**\S**                        | Bilo koji karakter koji *nije* razmak (belina), tabulator ili karakter za kraj reda

Klase znakova su lepe za skraćivanje regularnih izraza. Klasa znakova `[0-5]` podudaraće se samo sa brojevima od 0 do 5; ovo je mnogo kraće od kucanja 
`(0|1|2|3|4|5)`. Imajte na umu da `\d` odgovara ciframa, a `\w` podudara se sa ciframa, slovima i donjim crtama, to ne postoji stenografska klasa znakova koja se 
podudara samo sa slovima. (Iako možete da koristite klasu znakova `[a-zA-Z]`, kao što je objašnjeno u nastavku.)

Na primer, u interaktivnu ćeliju unesite sledeće:

In [85]:
xmasRegex = re.compile(r'\d+\s\w+')  #cifra 1+ puta, praznina, tipografski znak 1+ puta

In [88]:
xmasRegex.findall('12 drummers, 11 pipers, 10 lords, 9 ladies, 8 maids, 7 swans, 6 geese, 5 rings, 4 birds, 3 hens, 2 doves, 1 partridge')

['12 drummers',
 '11 pipers',
 '10 lords',
 '9 ladies',
 '8 maids',
 '7 swans',
 '6 geese',
 '5 rings',
 '4 birds',
 '3 hens',
 '2 doves',
 '1 partridge']

Regularni izraz `\d+\s\w+` poklapa se sa tekstom koji ima jednu ili više numeričkih cifara (`\d+`), a iza njega sledi razmak (`\s`), praćeni jednim ili više slova/cifara/donjih crta (`\w+`). Metoda `findall()` vraća sve podudarajuće stringove regularnog izraza na listi.

#### Konstruisanje sopstvenih klasa karaktera

Postoje slučajevi kada želite da podudarite/uparite skup znakova, ali stenografske klase znakova (`\d`, `\w`, `\s`, i tako dalje) su preširoke. Možete da definišete sopstvenu klasu znakova pomoću uglastih zagrada. Na primer, klasa znakova `[aeiouAEIOU]` podudaraće se sa bilo kojim samoglasnikom, malim i velikim. 

Unesite sledeće u interaktivnu ćeliju:

In [89]:
vowelRegex = re.compile(r'[aeiouAEIOU]')

In [90]:
vowelRegex.findall('RoboCop eats baby food. BABY FOOD.')

['o', 'o', 'o', 'e', 'a', 'a', 'o', 'o', 'A', 'O', 'O']

Opsege slova ili brojeva možete da dodate i pomoću crtice. Na primer, klasa znakova `[a-zA-Z0-9]` će odgovarati svim malim slovima, velikim slovima i brojevima.

Imajte na umu da se u uglastim zagradama normalni simboli regularnih izraza ne tumače kao takvi. To znači da ne morate da izbegnete znakove `.`, `*`,`?` ili `(` `)` sa prethodnom kosom kosom crtom. Na primer, klasa znakova `[0-5.]` podudaraće se sa ciframa od 0 do 5 i tačkom. Ne morate to pisati kao `[0-5 \.]`.

Postavljanjem znaka `^`(kvačica) odmah nakon uvodne zagrade klase znakova, možete da napravite *negativnu klasu karaktera*. Negativna klasa znakova podudaraće se sa svim znakovima koji nisu u klasi znakova. Na primer, u interaktivnu ćeliju unesite sledeće:

In [91]:
consonantRegex = re.compile(r'[^aeiouAEIOU]')

In [92]:
consonantRegex.findall('RoboCop eats baby food. BABY FOOD.')

['R',
 'b',
 'C',
 'p',
 ' ',
 't',
 's',
 ' ',
 'b',
 'b',
 'y',
 ' ',
 'f',
 'd',
 '.',
 ' ',
 'B',
 'B',
 'Y',
 ' ',
 'F',
 'D',
 '.']

Sada, umesto uparivanja svakog samoglasnika, uparuje se svaki karakter koji nije samoglasnik.

#### Karakteri `$` (dolar) i `^` (kvačica)

Možete koristiti kvačicu (`^`) na početku regularnog izraza da naznačite da se podudaranje mora dogoditi na početku traženog teksta. Isto tako, na kraj regularnog izraza možete staviti znak dolar (`$`) da biste označili da string mora da se završava datim šablonom regularnog izraza. A možete zajedno koristiti `^` i `$` da biste označili da ceo string mora odgovarati regularnom izrazu - to jest, nije dovoljno da se podudaranje desi na nekom delu stringa.

Na primer, regularni izraz `r'^ Hello'` podudara se sa stringovima koji počinju sa 'Hello'. Unesite sledeće u interaktivnu ćeliju:

In [93]:
beginsWithHello = re.compile(r'^Hello')

In [94]:
beginsWithHello.search('Hello, world!')

<re.Match object; span=(0, 5), match='Hello'>

In [95]:
beginsWithHello.search('He said hello.') == None

True

Regularni izraz `r'\d$'` podudara se sa stringovima koji se završavaju numeričkim znakom od 0 do 9. Unesite sledeće u interaktivnu ćeliju:

In [96]:
endsWithNumber = re.compile(r'\d$')

In [97]:
endsWithNumber.search('Your number is 42')

<re.Match object; span=(16, 17), match='2'>

In [98]:
endsWithNumber.search('Your number is forty two.') == None

True

Regularni izraz `r'^\d+$'` podudara se sa stringovima koji počinju i završavaju se jednim ili više numeričkih znakova. U interaktivnu ćeliju unesite sledeće:

In [99]:
wholeStringIsNum = re.compile(r'^\d+$')

In [100]:
wholeStringIsNum.search('1234567890')

<re.Match object; span=(0, 10), match='1234567890'>

In [101]:
wholeStringIsNum.search('12345xyz67890') == None

True

In [102]:
wholeStringIsNum.search('12 34567890') == None

True

Poslednja dva poziva `search()` u prethodnom primeru pokazuju kako se ceo string mora podudarati sa regularnim izrazom ako se koriste `^` i `$`.

Uvek mešam značenja ova dva simbola, pa koristim mnemotehniku „Šargarepa košta dolar“ da se podsetim da je kvačica prvom mestu, a znak dolara na poslednjem mestu.

#### Wildcard `.`(tačka) karakter

Znak za tačku (`.`) u regularnom izrazu naziva se zamenljivim znakom i podudaraće se sa bilo kojim znakom, osim sa novom linijom. Na primer, u interaktivnu ćeliju unesite sledeće:

In [103]:
atRegex = re.compile(r'.at')

In [104]:
atRegex.findall('The cat in the hat sat on the flat mat.')

['cat', 'hat', 'sat', 'lat', 'mat']

Imajte na umu da će se znak za tačku podudarati sa samo jednim znakom. Da biste napravili podudaranje sa stvarnom tačkom koristite `\.` (escape character `\`)

#### Uparivanje svega sa tačka-zvezda

Ponekad ćete želeti da uparujete/podudarate sa svim i svačim. Na primer, recimo da želite da se podudaranje sa stringom „Prezime:“, praćeno bilo kojim tekstom, zatim „Prezime:“, a zatim ponovo bilo šta. Tada može da se koristi tačka-zvezdu (`.*`) da se kaže za to „bilo šta“. Zapamtite da tačkasti znak znači „bilo koji pojedinačni znak osim novog reda “, a zvezdasti znak znači„ nula ili više prethodnog znaka “. U interaktivnu ćeliju unesite sledeće:

In [110]:
nameRegex = re.compile(r'Ime: (.*) Prezime: (.*)')

In [111]:
mo = nameRegex.search('Ime: Dragan Prezime: Azdejković')

In [112]:
mo.group(1)

'Dragan'

In [113]:
mo.group(2)

'Azdejković'

Tačka-zvezda koristi pohlepni režim: Uvek će pokušati da uskladi što više teksta. Da se podudara sa bilo kojim tekst na nepohlepni način, koristite tačku, zvezdicu 
i znak pitanja (. *?). Kao kod zagrada, znak pitanja govori Pithonu da se podudara na ne-pohlepan način.

U interaktivnu ćeliju unesite sledeće da biste videli razliku između pohlepnih i ne pohlepnih verzija:

In [114]:
nongreedyRegex = re.compile(r'<.*?>')

In [116]:
mo = nongreedyRegex.search('<Piletina> za ručak.>')

In [117]:
mo.group()

'<Piletina>'

In [118]:
greedyRegex = re.compile(r'<.*>')

In [119]:
mo = greedyRegex.search('<Piletina> za ručak.>')

In [120]:
mo.group()

'<Piletina> za ručak.>'

Oba regeksa se približno prevode u „Podudaraju se zagrada ugla otvaranja, praćena bilo čime, a zatim zatvarajući ugaona zagrada“, ali string `'<Piletina> za ručak.>'` ima dva moguća podudaranja za zatvaranje ugaonih zagrada. U ne pohlepnoj verziji regularnog izraza, Pithon podudara sa najkraćim mogućim stringom: `'<Piletina>'`. U pohlepnoj verziji Pithon se podudara sa najdužim mogućim nizom: `'<Piletina> za ručak.>'`.

#### Uparivanje nove linije sa tačkastim karakterom

Tačka-zvezda će se podudarati sa svim osim sa novom linijom. Predajom `re.DOTALL` kao drugog argumenta `re.compile()`, možete učiniti da se tačkasti znak podudara 
sa svim znakovima, uključujući i znak novog reda.

U interaktivnu ćeliju unesite sledeće:

In [ ]:
noNewlineRegex = re.compile('.*')

In [ ]:
noNewlineRegex.search('Serve the public trust.\nProtect the innocent.\nUphold the law.').group()

In [ ]:
newlineRegex = re.compile('.*', re.DOTALL)

In [ ]:
newlineRegex.search('Serve the public trust.\nProtect the innocent.\nUphold the law.').group()

Regeks `noNewlineRegex`, koji nema prosleđeno `re.DOTALL` metodu `re.compile`, uparivaće sve da prvog znaka za novu liniju, dok `noNewlineRegex`, koji ima 
prosleđeno `re.DOTALL` metodu `re.compile`, uparivaće sve. To je razlog zašto pozivanjem `newlineRegex.search()` uparuje ceo string uključujući i karakter 
za kraj reda.

#### Pregled Regeks simbola

Ovo poglavlje pokrivalo je puno notacija, pa evo kratkog pregleda onoga šta ste naučili o osnovnoj sintaksi regularnog izraza: 
    
- `?` zahteva podudaranje nula ili jednom sa grupom koja prethodi. 
- Znak `*` zahteva podudaranje nula ili više puta sa grupom koja prethodi. 
- Znak `+` zahteva podudaranje jednom ili više puta sa grupom koja prethodi. 
- Oznaka `{n}` zahteva podudaranje tačno $n$ puta sa grupom koja prethodi. 
- Oznaka `{n ,}` zahteva podudaranje najmanje $n$ puta sa grupom koja prethodi. 
- `{, m}` zahteva podudaranje najviše $m$ puta sa grupom koja prethodi. 
- `{n, m}` zahteva podudaranje najmanje $n$ i najviše $m$ puta sa grupom koja prethodi. 
- `{n, m}?` ili *? ili +? izvršava ne pohlepno podudaranje prethodne grupe. 
- `^spam` znači da string mora počinjati sa `spam`. 
- `spam\$` znači da se string mora završiti sa `spam`. 
- `.` podudara se sa bilo kojim znakom, osim znakova za novi red. 
- `\d`, `\w` i `\s` odgovaraju cifri, slovu ili razmaku, odnosno. 
- `\D`, `\W` i `\S` odgovaraju bilo čemu osim cifri, slovu ili razmaku znak. 
- `[abc]` se podudara sa bilo kojim znakom između zagrada (poput *a*, *b* ili *c*). 
- `[^abc]` se podudara sa bilo kojim znakom koji nije između zagrada.

#### Uparivanje osetljivo na veličinu slova

Obično se regularni izrazi podudaraju s tekstom sa tačnim slovima koje navedete. Na primer, sledeći regularni izrazi se podudaraju sa potpuno različitim stringovima:

In [121]:
regex1 = re.compile('RoboCop')
regex2 = re.compile('ROBOCOP')
regex3 = re.compile('robOcop')
regex4 = re.compile('RobocOp')

Ali ponekad vam je stalo samo da se slova podudaraju, ne brinući da li su velika ili mala. Da biste učinili da vaš regeks ne razlikuje velika i mala slova, možete 
dodati `re.IGNORECASE` ili `re.I` kao drugi argument u `re.compile()`. U interaktivnu ćeliju unesite sledeće:

In [122]:
robocop = re.compile(r'robocop', re.I)

In [123]:
robocop.search('RoboCop is part man, part machine, all cop.').group()

'RoboCop'

In [124]:
robocop.search('ROBOCOP protects the innocent.').group()

'ROBOCOP'

In [125]:
robocop.search('Al, why does your programming book talk about robocop so much?').group()

'robocop'

#### Zamena stringova metodom `sub()`

Regularni izrazi mogu ne samo da pronađu tekstualne obrasce, već mogu i zameniti novi tekst umesto tih obrazaca. Metodi `sub()` za Regeks objekte prosleđuju se dva 
argumenta. Prvi argument je string koji zamenjuje bilo koja podudaranja. Drugi je string za regularni izraz. Metoda `sub()` vraća string sa primenjenim zamenama.

Na primer, u interaktivnu ćeliju unesite sledeće:

In [126]:
namesRegex = re.compile(r'Agent \w+')

In [127]:
namesRegex.sub('CENSORED', 'Agent Alice gave the secret documents to Agent Bob.')

'CENSORED gave the secret documents to CENSORED.'

Ponekad ćete možda morati da koristite sam tekst koji se podudara kao deo zamene. U prvom argumentu za `sub()` možete otkucati `\1`, `\2`, `\3` i tako dalje, što 
znači „Unesite tekst grupe 1, 2, 3 i tako dalje, u zamenu.“

Na primer, recimo da želite da cenzurišete imena tajnih agenata tako što ćete prikazati samo prva slova njihovih imena. Da biste to uradili, možete koristiti 
regularni izraz `Agent`, `(\w)\w*`, i predati `r'\1****'` kao prvi argument `sub()`. `\1` u tom stringu biće zamenjen bilo kojim tekstom koji se podudara sa 
grupom 1 - to jest, `(\w)` grupom regularnog izraza.

In [128]:
agentNamesRegex = re.compile(r'Agent (\w)\w*')

In [129]:
agentNamesRegex.sub(r'\1****', 'Agent Alice told Agent Carol that Agent Eve knew Agent Bob was a double agent.')

'A**** told C**** that E**** knew B**** was a double agent.'

#### Upravljanje složenim regeksima

Regularni izrazi su u redu ako je obrazac teksta koji treba da se podudara jednostavan. Ali podudaranje složenih tekstualnih obrazaca može zahtevati dugačke, 
zamršene regularne izraze. To možete ublažiti rekavši funkciji `re.compile()` da zanemari razmake i komentare unutar stringa regularnog izraza. Ovaj „opširan režim“ 
može se omogućiti dodavanjem promenljive `re.VERBOSE` kao drugog argumenta u `re.compile()`.

Sada umesto ovako čitljivog regularnog izraza:

In [130]:
phoneRegex = re.compile(r'((\d{3}|\(\d{3}\))?(\s|-|\.)?\d{3}(\s|-|\.)\d{4}(\s*(ext|x|ext.)\s*\d{2,5})?)')

regularni izraz možete proširiti na više redova sa komentarima poput ovog:

In [131]:
phoneRegex = re.compile(r'''(
     (\d{3}|\(\d{3}\))?            # area code
     (\s|-|\.)?                    # separator
     \d{3}                         # first 3 digits
     (\s|-|\.)                     # separator
     \d{4}                         # last 4 digits
    (\s*(ext|x|ext.)\s*\d{2,5})?   # extension
     )''', re.VERBOSE)

Obratite pažnju na to kako prethodni primer koristi sintaksu sa trostrukim navodnicima (`'''`) za stvaranje višerednog stringa, tako da možete proširiti definiciju regularnog izraza na više linija, čineći ga mnogo čitljivijim.

Pravila za komentare unutar stringa regularnog izraza ista su kao i kod regularnog Pithona: simbol # i sve nakon njega do kraja reda se zanemaruju. Takođe, dodatni razmaci unutar višerednog stringa za regularni izraz ne smatraju se delom šablona teksta koji treba podudarati. Ovo vam omogućava da organizujete regularni izraz tako da ga je lakše čitati.

#### Kombinovanje `re.IGONORECASE`, `re.DOTALL` i `re.VERBOSE`

Šta ako želite da koristite `re.VERBOSE` za pisanje komentara u svoj regularni izraz, ali takođe želite da koristite `re.IGNORECASE` da biste zanemarili upotrebu 
velikih slova? Nažalost, funkcija `re.compile()` uzima samo jednu vrednost kao drugi argument. Ovo ograničenje možete zaobići kombinovanjem promenljivih 
`re.IGNORECASE`, `re.DOTALL` i `re.VERBOSE` koristeći znak cevi (|), koji je u ovom kontekstu poznat kao bitni ili operator.

Dakle, ako želite regularni izraz koji ne razlikuje velika i mala slova i uključuje nove redove koji se podudaraju sa tačkastim znakom, formirali biste svoj poziv 
`re.compile()` ovako:

In [ ]:
someRegexValue = re.compile('foo', re.IGNORECASE | re.DOTALL)

Uključivanje sve tri opcije kao drugi argument bi izgleadalo ovako:

In [ ]:
someRegexValue = re.compile('foo', re.IGNORECASE | re.DOTALL | re.VERBOSE)

Ova sintaksa je pomalo staromodna i potiče iz ranih verzija Pithona. Detalji bitnih operatora su izvan opsega ove knjige, ali potražite resurse na 
https://nostarch.com/automatestuff2/ za više informacija. Takođe možete proslediti druge opcije za drugi argument; oni su neuobičajeni, 
ali više o njima možete pročitati i u resursima.

### Projekat: Ekstraktor telefonskog broja i e-mail adrese

Recimo da imate dosadan zadatak da pronađete svaki telefonski broj i adresu e-pošte na dugoj veb stranici ili dokumentu. Ako ručno skrolujete po stranici, možda ćete na kraju potrošiti duže vreme. Ali ako biste imali program koji bi mogao pretraživati brojeve telefona i adrese e-pošte u tekstu, možete jednostavno pritisnuti CTRL-A da biste izabrali sav tekst, pritisnite CTRL-C da biste ga kopirali u privremeno skladište ili datoteku, a zatim pokreniti program. Rezultate sa brojevima telefona i adresama e-pošte koje pronađete možete sačuvati u posebnoj datoteci ili skladištu.

Kad god se bavite novim projektom, može biti primamljivo zaroniti pravo u pisanje koda. Ali najčešće je najbolje napraviti korak unazad i razmotriti širu sliku. Preporučujem da prvo napravite plan na visokom nivou za ono što vaš program treba da uradi. Ne razmišljajte još o stvarnom kodu - o tome možete brinuti kasnije. 
Trenutno se držite širokih poteza.

Na primer, ekstraktor brojeva telefona i adrese e-pošte moraće da uradi sledeće: 
    
1. Skiniti tekst iz skladišta. 
2. Pronaći sve brojeve telefona i adrese e-pošte u tekstu. 
3. Zalepiti ih u skladište ili sačuvati u datoteci.

Sada možete početi da razmišljate o tome kako bi ovo moglo funkcionisati u kodu. Kod će morati uraditi sledeće: 
    
1. Koristite `piperclip` modul da kopirate i nalepite stringove.
2. Napravite dva regularna izraza, jedan za podudaranje brojeva telefona i drugi za podudaranje adresa e-pošte.
3. Pronađite sva podudaranja, ne samo prvi match, sa oba regeksa.
4. Uredno formatirajte podudarne stringove u jedan string za lepljenje.
5. Prikazati neku vrstu poruke ako u tekstu nisu pronađena podudaranja.

Ova lista je poput mape puta za projekat. Dok pišete kod, možete se posebno usredsrediti na svaki od ovih koraka. Svaki korak je prilično jasan i izražen je stvarima koje već znate kako da radite u Pithonu.

#### Korak 1: Kreiranje regeksa sa broj telefona

Prvo morate da kreirate regularni izraz za traženje telefonskih brojeva. Napravite novu datoteku, unesite sledeće i sačuvajte je kao *phoneAndEmail.py*:

```python
# phoneAndEmail.py - Pronalazi brojeve telefona i e-mail adrese u skladištu (eng. clipboard).

import pyperclip, re

phoneRegex = re.compile(r'''(
    (\d{3}|\(\d{3}\))?                # area code
    (\s|-|\.)?                        # separator
    (\d{3})                           # first 3 digits
    (\s|-|\.)                         # separator
    (\d{4})                           # last 4 digits
    (\s*(ext|x|ext.)\s*(\d{2,5}))?    # extension
    )''', re.VERBOSE)

# TODO: Create email regex.

# TODO: Find matches in clipboard text.

# TODO: Copy results to the clipboard.
```

TODO komentari su samo kostur programa. Oni će biti zamenjeni dok pišete stvarni kod.

Telefonski broj započinje opcionim pozivnim brojem, pa se grupa pozivnog broja prati znakom pitanja. Budući da pozivni broj može biti samo tri cifre (to jest, `\d{3}`) ili tri cifre u zagradama (to jest, `\(\d{3}\)`), trebali biste imati cev koja spaja te delove. U ovaj deo višerednog stringa možete dodati komentar regularnog izraza # Pozivni broj,  kako biste se setili sa čim `(\d{3}|\(\d{3}\))`? treba da se podudara.

Znak za razdvajanje broja telefona može biti razmak (`\s`), crtica (`-`) ili tačka (`.`), pa bi ovi delovi takođe trebalo da budu spojeni cevima. Sledećih nekoliko delova regularnog izraza je jednostavan: tri cifre, zatim još jedan separator, a zatim četiri cifre. Poslednji deo je opciono proširenje koje se sastoji od bilo kog broja razmaka praćenih ext, x ili ext., Nakon čega slede dve do pet cifara.

NAPOMENA: Lako je pomešati u regularnim izrazima koji sadrže grupe sa zagradama () i pregradnim zagradama `\(` `\)`. Ne zaboravite da dvaput proverite da li koristite ispravnu ako se prikaže poruka o grešci „missing), unterminated subpattern“.

#### Korak 2: Kreiranje regeksa za e-mail adrese

Takođe će vam trebati regularni izraz koji se može uparivati adrese e-pošte. Neka vaš program izgleda ovako:

```python

# phoneAndEmail.py - Finds phone numbers and email addresses on the clipboard.

import pyperclip, re

phoneRegex = re.compile(r'''(
--snip--

# Create email regex.
emailRegex = re.compile(r'''(
  [a-zA-Z0-9._%+-]+      # username
  @                      # @ symbol
  [a-zA-Z0-9.-]+         # domain name
  (\.[a-zA-Z]{2,4})      # dot-something
  )''', re.VERBOSE)

 # TODO: Find matches in clipboard text.

 # TODO: Copy results to the clipboard.
```

Korisnički deo adrese e-pošte je jedan ili više znakova koji mogu biti bilo koji od sledećih: mala i velika slova, brojevi, tačka, donja crta, znak procenta, znak plusa ili crtica. Sve ovo možete staviti u klasu znakova: `[a-zA-Z0-9 ._% + -]`.

Domen i korisničko ime odvojeni su znakom `@`. Ime domena ima nešto manje popustljivu klasu znakova sa samo slovima, brojevima, tačkama i crticama: `[a-zA-Z0-9.-]`. I poslednji će biti „dot-com“ deo (tehnički poznat kao domen najvišeg nivoa), koji zaista može biti tačka-bilo šta. Ovo je između dva i četiri znaka.

Format adresa e-pošte ima puno čudnih pravila. Ovaj regularni izraz neće se podudarati sa svakom mogućom važećom adresom e-pošte, ali će se podudarati sa gotovo svakom tipičnom adresom e-pošte sa kojom ćete se susresti.

#### Korak 3: Pronalaženje svih uparivanja sa tekstom u skladištu (Clipbordu)

Sada kada ste naveli regularne izraze za brojeve telefona i adrese e-pošte, možete da dozvolite Pithon-ovom re modulu da izvrši težak posao pronalaženja svih 
podudaranja u skladištu. Funkcija `piperclip.paste()` će dobiti vrednost stringa teksta u privremenu memoriju, a regeks metoda `findall()` vratiće listu nizova.

Neka vaš program izgleda ovako:

```python
# Find matches in clipboard text.
text = str(pyperclip.paste())

#A
matches = []  
#B
for groups in phoneRegex.findall(text):
    phoneNum = '-'.join([groups[1], groups[3], groups[5]])
    if groups[8] != '':
        phoneNum += ' x' + groups[8]
        matches.append(phoneNum)
#C
for groups in emailRegex.findall(text):
    matches.append(groups[0])       
```

Za svako podudaranje postoji po jedan niz, a svaki niz sadrži stringove za svaku grupu u regularnom izrazu. Imajte na umu da se grupa 0 podudara sa celim regularnim izrazom, tako da je grupa sa indeksom 0 ona koja vas zanima.

Kao što vidite, podudaranja ćete sačuvati u promenljivoj listi koja se zove `matches` (deo `#A`). Počinje kao prazna lista i ulazimo u petlju. Za adrese e-pošte dodajete grupu 0 svakog podudaranja  u listu (deo `#C`). Za podudarne brojeve telefona ne želite da dodate samo grupu 0. 

Iako program otkriva telefonske brojeve u nekoliko formata, želite da dodati telefonski broj bude u jednom, standardnom formatu. Promenljiva `phoneNum` sadrži string izgrađen od grupa 1, 3, 5 i 8 podudarnog teksta (deo `#B`). (Ove grupe su pozivni broj, prve tri cifre, poslednje četiri cifre i ekstenzija.)

#### Korak 4: Spajanje uparenog u string za Clipboard

Sada kada imate adrese e-pošte i brojeve telefona kao listu nizova u podudaranjima, želite da ih stavite u clipboard. Funkcija `piperclip.copy()` uzima samo jednu vrednost stringa, a ne listu stringova, pa na podudaranjima pozivate metodu `join()`.

Da bismo olakšali uvid u to kako program radi, odštampajmo sve terme koje pronađete na ekranu. Ako nisu pronađeni brojevi telefona ili adrese e-pošte, program to treba da saopšti korisniku.

Neka vaš program izgleda ovako:

```python

phoneAndEmail.py - Finds phone numbers and email addresses on the clipboard.

--snip--
for groups in emailRegex.findall(text):
     matches.append(groups[0])

# Copy results to the clipboard.
if len(matches) > 0:
    pyperclip.copy('\n'.join(matches))
    print('Copied to clipboard:')
    print('\n'.join(matches))
else:
    print('No phone numbers or email addresses found.')
```

#### Pokretanje programa

Na primer, otvorite veb pregledač na stranici https://nostarch.com/contactus/, pritisnite CTRL-A da biste izabrali sav tekst na stranici i pritisnite CTRL-C da 
biste ga kopirali na clipboard. Kada pokrenete ovaj program, izlaz će izgledati otprilike ovako:

### Ideje za sličan program

Identifikovanje obrazaca teksta (i eventualna zamena metodom `sub()`) ima mnogo različitih potencijalnih primena. Na primer, mogli biste: 
    
- da pronađete URL adrese veb lokacija koje počinju sa http:// ili https://.
- Čistite datume u različitim formatima datuma (kao što su 14.3.2019, 14.03.2019 i 2015/3/19) tako što će ih zameniti datumima u jednom standardnom formatu. 
- Ukloniti osetljive informacije kao što su brojevi socijalnog osiguranja ili brojevi kreditnih kartica. 
- Pronaći uobičajene greške u kucanju, kao što su više razmaka između reči, slučajno ponovljene reči ili više znakova uskličnika na kraj rečenica. To su dosadne !!

#### Sumarum

Iako računar može brzo da pretražuje tekst, mora mu se tačno reći šta treba tražiti. Regularni izrazi vam omogućavaju da odredite obrazac znakova koje tražite, 
a ne tačan sam tekst. U stvari, neke aplikacije za obradu teksta i proračunske tabele pružaju funkcije pronađi i zameni koje ti omogućavaju pretragu pomoću 
regularnih izraza.

Modul `re` koji dolazi sa Pithonom omogućava vam kompajliranje Regex objekata. Ovi objekti imaju nekoliko metoda: `search()` za pronalaženje pojedinačnog 
podudaranja, `findall()` za pronalaženje svih podudarnih instanci i `sub()` za pronalaženje i zamenu teksta.

Više možete saznati u službenoj Pithon dokumentaciji na https://docs.python.org/3/librari/re.html. Još jedan koristan resurs je veb stranica sa vodičima 
https://www.regular-expressions.info/.

#### Praktična pitanja

1. Koja je funkcija koja stvara `Regex` objekte?
2. Zašto se sirovi stringovi često koriste prilikom kreiranja `Regex` objekata?
3. Šta vraća metoda `search()`?
4. Kako iz objekta `Match` dobijete stvarne stringove koji se podudaraju sa šablonom?
5. U regularnom izrazu kreiranom od `r'(\d\d\d)-(\d\d\d-\d\d\d\d)'`, šta obuhvata grupa 0? Grupa 1? Grupa 2?
6. Zagrade i tačke imaju specifična značenja u sintaksi regularnog izraza. Kako biste naveli da želite da se regularni izraz podudara sa stvarnim zagradama i znakovima tačke?
7. Metoda `findall()` vraća listu nizova ili listu nizova od stringova. Zbog čega se vraća jedno ili drugo?
8. Šta znači | znak u regularnim izrazima?
9. Koje dve stvari radi ? znak u regularnim izrazima?
10. Koja je razlika između znakova + i * u regularnim izrazima?
11. Koja je razlika između {3} i {3,5} u regularnim izrazima?
12. Šta označavaju klase karaktera `\d`, `\w` i `\s` u regularnim izrazima?
13. Šta označavaju klase karatera `\D`, `\W` i `\S` u regularnim izrazima?
14. Koja je razlika između `.*` i `.*?`?
15. Koja je sintaksa klase znakova koja se podudara sa svim brojevima i malim slovima?
16. Kako praviš da regularni izraz ne razlikuje velika i mala slova?
17. Sa čime se karakter `.` normalno podudara? Šta se podudara ako se `re.DOTALL` preda kao drugi argument za `re.compile()`?
18. Ako je `numRegex = re.compile (r'\d+')`, šta će vratiti `numRegex.sub ('Ks', '12 bubnjara, 11 lula, pet prstenova, 3 kokoši ')`?
19. Šta vam omogućava dodavanje `re.VERBOSE` kao drugog argumenta za `re.compile()`?
20. Kako biste napisali regularni izraz koji odgovara broju i zapetama za svake tri cifre? Mora odgovarati sledećem: '42', '1,234', '6,368,745',  ali ne i sledećem: 
   '12, 34,567 '(koja ima samo dve cifre između zareza), ' 1234 '(kojoj nedostaju zarezi)
21. Kako biste napisali regularni izraz koji se podudara sa punim imenom nekoga ko se preziva Vatanabe? Možete pretpostaviti da će prvo ime koje dolazi pre njega uvek biti jedna reč koja počinje velikim slovom. Redovni izraz mora odgovarati sledećem: 'Haruto Vatanabe', 'Alice Vatanabe', 'RoboCop Vatanabe', ali ne i sledećem: 'haruto Vatanabe' (gde ime nije napisano velikim slovom), 'Mr. Vatanabe '(gde prethodna reč ima neslovni karakter), ' Vatanabe '(bez imena), ' Haruto vatanabe '(gde Vatanabe nije napisana velikim slovom)
22. Kako biste napisali regularni izraz koji se podudara sa rečenicom u kojoj je prva reč Alice, Bob ili Carol; druga reč je ili jede, ljubimce ili baca; treća reč su jabuke, mačke ili lopte; a rečenica se završava tačkom? Ovaj regularni izraz ne bi trebalo da razlikuje velika i mala slova. Mora se podudarati sa sledećim: 'Alice jede jabuke.', 'Bob maci mačke.',  'Carol baca lopte', 'Alice baca jabuke.', 'BOB JE MAČKA', ali ne i sledeće: 'RoboCop jede jabuke.', 'ALICE BACA NOGU.', 
'Carol jede 7 mačaka'.

### Praktični projekti

Kao vežbanje, napišite programe koji će uraditi sledeće zadatke.

#### Detekcija datuma

Napišite regularni izraz koji može otkriti datume u formatu DD/MM/GGGG. Pretpostavimo da se dani kreću od 01 do 31, meseci od 01 do 12, a godine od 1000 do 2999. 
Imajte na umu da ako je dan ili mesec jednocifren, imaće vodeću nulu.

Regularni izraz ne mora da otkriva tačne dane za svaki mesec ili za prestupnu godinu; prihvatiće nepostojeće datume poput 31/02/2020 ili 31/04/2021. Zatim te 
stringove sačuvajte u promenljive sa imenom mesec, dan i godina i napišite dodatni kod koji može otkriti da li je to valjani datum. April, jun, septembar i novembar 
imaju 30 dana, februar 28 dana, a ostatak meseci 31 dan. Februar ima 29 dana u prestupnoj godini. Prestupne godine su svake godine ravnomerno deljive sa 4, 
osim godina ravnomerno deljivih sa 100, osim ako je godina takođe ravnomerno deljiva sa 400. Obratite pažnju kako ovaj proračun onemogućava pravljenje regularnog 
izraza razumne veličine koji može otkriti valjani datum.

#### Detekcija jakog passworda

Napišite funkciju koja koristi regularne izraze kako bi bila sigurna da je string lozinke koji je prosleđen jak. Jaka lozinka je definisana kao lozinka koja ima 
najmanje osam znakova, sadrži velika i mala slova i ima najmanje jednu cifru. Možda ćete trebati da testirate string na osnovu višestrukih regularnih izraza da 
biste potvrdili njegovu snagu.

#### Regex verzija metoda `strip()`

Napišite funkciju koja uzima string i radi isto što i string metoda `strip()`. Ako se ne dodaju drugi argumenti osim stringa za uklanjanje, razmaci će se ukloniti 
s početka i kraja stringa. U suprotnom, znakovi navedeni u drugom argumentu funkcije biće uklonjeni iz stringa.